### ISSUE TITLE
Code issues nd construction

### ISSUE THREAD

**Issue by Syambotla** [Elysian01/Traffic-Light-Control#1]
Sir I got aa issues in sources code sir it shows error sir can u plz help me sir to slove sir 
@Elysian01

**Comment by Syambotla** [comment]
Plz sir response fast sir ☹️☹️☹️

**Comment by Elysian01** [comment]
You have to download the respective library, you can refer to this blog https://randomnerdtutorials.com/rf-433mhz-transmitter-receiver-module-with-arduino/
